"""olcum yerel kimlik

Revision ID: fc3d51b6229a
Revises: eb1fe4825cd3
Create Date: 2026-08-29 00:35:10.920276
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = 'fc3d51b6229a'
down_revision = 'eb1fe4825cd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olcum', sa.Column('yerel_kimlik', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_olcum_yerel_kimlik'), 'olcum', ['yerel_kimlik'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_olcum_yerel_kimlik'), table_name='olcum')
    op.drop_column('olcum', 'yerel_kimlik')
    # ### end Alembic commands ###
