"""ilk sema

Revision ID: eb1fe4825cd3
Revises: 
Create Date: 2026-08-27 12:15:09.066792
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = 'eb1fe4825cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eposta', sa.String(length=255), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('yonetici', 'afad', 'belediye', 'saha', 'uzman', 'yikim', 'tesis', name='rol_turu'), nullable=True),
    sa.Column('onay_durumu', sa.Enum('beklemede', 'onaylandi', 'reddedildi', name='onay_durumu_turu'), server_default='beklemede', nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kullanici_eposta'), 'kullanici', ['eposta'], unique=True)
    op.create_table('enkaz_alani',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('konum', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sinir', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('erisim_durumu', sa.Enum('acik', 'kisitli', 'kapali', name='erisim_durumu_turu'), server_default='acik', nullable=False),
    sa.Column('sorumlu', sa.String(length=200), nullable=True),
    sa.Column('inceleme_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['olusturan_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('islem_gecmisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kayit_tipi', sa.String(length=60), nullable=False),
    sa.Column('kayit_id', sa.Integer(), nullable=True),
    sa.Column('islem', sa.String(length=20), nullable=False),
    sa.Column('eski_deger', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('yeni_deger', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_islem_gecmisi_kayit_id'), 'islem_gecmisi', ['kayit_id'], unique=False)
    op.create_index(op.f('ix_islem_gecmisi_kayit_tipi'), 'islem_gecmisi', ['kayit_tipi'], unique=False)
    op.create_table('goruntu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enkaz_alani_id', sa.Integer(), nullable=False),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=False),
    sa.Column('konum', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('cekim_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cihaz', sa.String(length=200), nullable=True),
    sa.Column('kalite_durumu', sa.String(length=50), nullable=True),
    sa.Column('kalite_notu', sa.Text(), nullable=True),
    sa.Column('genislik', sa.Integer(), nullable=True),
    sa.Column('yukseklik', sa.Integer(), nullable=True),
    sa.Column('yukleyen_id', sa.Integer(), nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enkaz_alani_id'], ['enkaz_alani.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yukleyen_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goruntu_enkaz_alani_id'), 'goruntu', ['enkaz_alani_id'], unique=False)
    op.create_table('tespit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goruntu_id', sa.Integer(), nullable=False),
    sa.Column('sinif', sa.String(length=50), nullable=False),
    sa.Column('guven_skoru', sa.Float(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bbox_format', sa.String(length=50), nullable=False),
    sa.Column('konum', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('dogrulama_durumu', sa.Enum('beklemede', 'onaylandi', 'duzeltildi', 'belirsiz', name='dogrulama_durumu_turu'), server_default='beklemede', nullable=False),
    sa.Column('dogrulayan_id', sa.Integer(), nullable=True),
    sa.Column('dogrulama_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duzeltilen_sinif', sa.String(length=50), nullable=True),
    sa.Column('inceleme_gerekli', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("bbox_format <> ''", name='ck_tespit_bbox_format_dolu'),
    sa.CheckConstraint('guven_skoru >= 0 AND guven_skoru <= 1', name='ck_tespit_guven_araligi'),
    sa.ForeignKeyConstraint(['dogrulayan_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['goruntu_id'], ['goruntu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tespit_dogrulama_durumu'), 'tespit', ['dogrulama_durumu'], unique=False)
    op.create_index(op.f('ix_tespit_goruntu_id'), 'tespit', ['goruntu_id'], unique=False)
    op.create_index(op.f('ix_tespit_inceleme_gerekli'), 'tespit', ['inceleme_gerekli'], unique=False)
    op.create_index(op.f('ix_tespit_sinif'), 'tespit', ['sinif'], unique=False)
    op.create_table('miktar_hesabi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tespit_id', sa.Integer(), nullable=False),
    sa.Column('deger_alt', sa.Float(), nullable=False),
    sa.Column('deger_ust', sa.Float(), nullable=False),
    sa.Column('birim', sa.String(length=20), nullable=False),
    sa.Column('kullanilan_katsayi', sa.Float(), nullable=False),
    sa.Column('katsayi_kaynagi', sa.String(length=300), nullable=False),
    sa.Column('yontem', sa.String(length=300), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deger_alt <= deger_ust', name='ck_miktar_aralik_tutarli'),
    sa.CheckConstraint('deger_alt >= 0', name='ck_miktar_alt_negatif_degil'),
    sa.CheckConstraint('deger_ust > deger_alt', name='ck_miktar_araliksiz_degil'),
    sa.ForeignKeyConstraint(['tespit_id'], ['tespit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miktar_hesabi_tespit_id'), 'miktar_hesabi', ['tespit_id'], unique=True)
    op.create_table('olcum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tespit_id', sa.Integer(), nullable=False),
    sa.Column('tur', sa.Enum('alan', 'hacim', 'agirlik', name='olcum_turu'), nullable=False),
    sa.Column('deger', sa.Float(), nullable=False),
    sa.Column('birim', sa.String(length=20), nullable=False),
    sa.Column('yontem', sa.String(length=200), nullable=False),
    sa.Column('giren_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deger > 0', name='ck_olcum_deger_pozitif'),
    sa.ForeignKeyConstraint(['giren_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['tespit_id'], ['tespit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_olcum_tespit_id'), 'olcum', ['tespit_id'], unique=False)
    op.create_table('tehlikeli_kayit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tespit_id', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('incelemeye_yonlendirildi', 'lab_sonucu_var', name='tehlikeli_durum_turu'), nullable=False),
    sa.Column('lab_sonucu_notu', sa.Text(), nullable=True),
    sa.Column('giren_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['giren_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['tespit_id'], ['tespit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tehlikeli_kayit_tespit_id'), 'tehlikeli_kayit', ['tespit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tehlikeli_kayit_tespit_id'), table_name='tehlikeli_kayit')
    op.drop_table('tehlikeli_kayit')
    op.drop_index(op.f('ix_olcum_tespit_id'), table_name='olcum')
    op.drop_table('olcum')
    op.drop_index(op.f('ix_miktar_hesabi_tespit_id'), table_name='miktar_hesabi')
    op.drop_table('miktar_hesabi')
    op.drop_index(op.f('ix_tespit_sinif'), table_name='tespit')
    op.drop_index(op.f('ix_tespit_inceleme_gerekli'), table_name='tespit')
    op.drop_index(op.f('ix_tespit_goruntu_id'), table_name='tespit')
    op.drop_index(op.f('ix_tespit_dogrulama_durumu'), table_name='tespit')
    op.drop_table('tespit')
    op.drop_index(op.f('ix_goruntu_enkaz_alani_id'), table_name='goruntu')
    op.drop_table('goruntu')
    op.drop_index(op.f('ix_islem_gecmisi_kayit_tipi'), table_name='islem_gecmisi')
    op.drop_index(op.f('ix_islem_gecmisi_kayit_id'), table_name='islem_gecmisi')
    op.drop_table('islem_gecmisi')
    op.drop_table('enkaz_alani')
    op.drop_index(op.f('ix_kullanici_eposta'), table_name='kullanici')
    op.drop_table('kullanici')
    # ### end Alembic commands ###
